#!/bin/sh
set -e
# Automatically added by dh_php
for conf in blitz; do
    dpkg-maintscript-helper rm_conffile /etc/php/mods-available/${conf}.ini -- "$@"
done

if [ -e /usr/lib/php/php-maintscript-helper ] ; then
    . /usr/lib/php/php-maintscript-helper

    for version in 8.1 8.0 7.4 7.3 7.2 7.1 7.0 ; do
        for conf in blitz ; do
            php_invoke enmod $version ALL $conf || exit $?
	done
    done
else
    for conf in blitz ; do
        phpenmod $conf
    done
fi
# End automatically added section
